#!/usr/bin/env bash

LOCK="/tmp/regip"
[[ -e "${LOCK}" ]] && exit 0
/usr/bin/touch "${LOCK}"

DYNDNS_SRV="https://sev.spacescience.ro"
APP_PATH="/dnsmasq/reg.php?"
SRV_URL="${DYNDNS_SRV}${APP_PATH}"

GW="$(/sbin/ip -4 r | /usr/bin/awk '/default/ {print $3}')"
IP_DYN=$(/usr/sbin/ip -4 -o a s | /usr/bin/awk '/dynamic/ {split($4,arr,"/");print arr[1]}') #'
[[ -z "${IP_DYN}" ]] && { echo "No dynamic ip found, fixed ips cand be manually registered"; exit 1; }

if [[ "${1}" == "priv" ]]; then
  # we want only private addresses (we expect that the public ones even if dynamic are registered in dns)
  IPs="$(/bin/grep -P '/(^127\.)|(^192\.168\.)|(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)/' <<< "${IP_DYN}")" #'
else # use whatever dynamic IP
  IPs="${IP_DYN}"
fi

# IF there are multiple dhcp ips on the interface lets select one
IP="$(/usr/bin/head -n1 <<< "${IPs}")"
/usr/bin/curl -fslk --retry 3 --header "Forwarded: ${IP}" "${SRV_URL}$(/bin/hostname)"

/bin/rm -rf "${LOCK}"

