#!/usr/bin/env bash

CURL="/usr/bin/curl -sfSLk"

REGIP_ARG="${1}"

mkdir -p /root/bin
cd /root/bin/
${CURL} -O https://raw.githubusercontent.com/adriansev/dyndns_home/master/regip
chmod +x regip

echo "@reboot root /root/bin/regip ${REGIP_ARG} &>/dev/null
*/10 * * * * root /root/bin/regip ${REGIP_ARG} &>/dev/null
" > /etc/cron.d/regip

