#!/usr/bin/env bash

mkdir -p /root/bin && cd /root/bin || { echo "cannot cd to /root/bin"; exit 1; }
/usr/bin/curl -sfSLk https://raw.githubusercontent.com/adriansev/dyndns_home/master/regip -o /root/bin/regip && chmod +x regip

echo "
@reboot      root /root/bin/regip ${@} &>/dev/null
*/10 * * * * root /root/bin/regip ${@} &>/dev/null
" > /etc/cron.d/regip

